### ISSUE TITLE
[BUG] Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by Asteb612** [refinedev/refine#5014] opened 2023-09-26 09:57 UTC
### Describe the bug

If `useQueryClient` is used to invalidate data on NextJS Layout this raise this error `Error: No QueryClient set, use QueryClientProvider to set one`.

I have already found a workaround that is to define a `QueryClientProvider` parent of Refine. I think the source of this bug is Layout have been rendered before the QueryClientProvider. But i'm not sure if that will create some side effects.

### Steps To Reproduce

1. Define queryClient in _app.js with useState cache.
2. Extend MyApp with Layout. I use typescript.
```
type NextPageWithLayout<P = object | undefined, IP = P> = NextPage<
  P,
  IP
> & {
  noTemplate?: boolean
  getLayout?: (page: ReactElement, pageProps: AppProps) => ReactNode
}
type ExtendedAppProps = AppProps & {
  Component: NextPageWithLayout
}

function MyApp({ Component, pageProps }: ExtendedAppProps): JSX.Element {
  const [queryClient] = useState<QueryClient>(new QueryClient())

  const getLayout = useMemo(
    () => Component.getLayout ?? ((page: ReactElement) => page),
    [Component]
  )

  const ComponentWithLayout: React.FC<{
    children: JSX.Element
  }> = ({ children }): ReactNode => {
    return getLayout(children, pageProps)
  }

  return (
    <Refine
      options={{
        reactQuery: {
          clientConfig: queryClient,
        },
    }}
    ...>
          <ComponentWithLayout>
            <Component {...pageProps} />
          </ComponentWithLayout>
</Refine>
```
3. Create some layout
```
const Layout: React.FC<{
  children: ReactElement
}> = ({ children }) => {
  const queryClient = useQueryClient()
  return (
    <div>{children}</div>
  )
}
```
4. Create page with layout
```
Page.getLayout = (page: ReactElement, pageProps: AppProps) => (
    <Layout>
      {page}
    </Layout>
)
5. Reload the page. The bug happen during the hard refresh.

### Expected behavior

I guess no error or some explanation about what i have done wrong :-p

### Screenshot

_No response_

### Desktop

"@refinedev/antd": "^5.36.2",
"@refinedev/cli": "^2.15.2",
"@refinedev/core": "^4.42.0",
"@refinedev/hasura": "^6.4.6",
"@refinedev/inferencer": "^4.5.12",
"@refinedev/nextjs-router": "^5.5.0",
"@refinedev/react-hook-form": "^4.8.8",


### Mobile

_No response_

### Additional Context

In the same layout i also have `useInvalidate` but no problem with it...

**Comment by Asteb612** [comment] 2023-09-26 14:43
Hello @BatuhanW my specific use case is related to cypress. And resetting QueryClient cache on e2e tests.
But i have the same issue without initializing the queryclient and manually pass it.

**Comment by BatuhanW** [comment] 2023-09-27 08:17
Hello @Asteb612 we have `with-nextjs` example, can you check this example and see what you are missing? 

https://github.com/refinedev/refine/blob/28fe67047a084dff37fbdbee6a132f85f9413657/examples/with-nextjs/pages/_app.tsx

You can also use this command to copy this example to your local.

`npm create refine-app@latest -- --example with-nextjs`

I'm closing the issue since most probably it's not a bug with refine.

However, if your problem still persists, you can re-open this issue and provide us a minimal reproducible example, so we can help.

**Closed by BatuhanW** 2023-09-27 08:17 UTC
Labels: bug
