### ISSUE TITLE
[BUG] default MUI theme shrinks the main content when sidebar is open initially, but not whenever the sidebar is opened after that

### ISSUE THREAD

**Issue by ThomasBurgess2000** [refinedev/refine#6197] opened 2024-07-26 18:49 UTC
### Describe the bug

As you can see in the official Refine MUI docs, when you first load the table, the sidebar is open and the entire table is visible (it is resized to fit). However, if you close the sidebar and then reopen it, it covers the first few columns of the table. Why would this behavior change?

### Steps To Reproduce

1. Go to https://refine.dev/docs/ui-integrations/material-ui/introduction/
2. Close the sidebar
3. Reopen the sidebar

### Expected behavior

Consistently resize the table to fit, rather than having the sidebar cover it when reopening

### Packages

"@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.53.0",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/kbar": "^1.3.6",
    "@refinedev/mui": "^5.19.4",
    "@refinedev/nextjs-router": "^6.0.0",
    "@refinedev/react-hook-form": "^4.8.14",
    "@refinedev/simple-rest": "^5.0.1",

**Comment by ThomasBurgess2000** [comment] 2024-07-26 19:25
Deleting `{overflow: "clip"}` fixed this: https://github.com/refinedev/refine/blame/c61c4143dd1e343c7323a015d8aee858c5d24dee/packages/mui/src/components/themedLayoutV2/index.tsx#L35

Not sure why it has two `overflow` defined

**Comment by aliemir** [comment] 2024-07-26 19:27
Hey @ThomasBurgess2000, sorry for the issue. This is a duplicate of https://github.com/refinedev/refine/issues/6077. It's fixed with https://github.com/refinedev/refine/pull/6144 and will be released next week with our August release 🙏

**Closed** 2024-07-26 19:27 UTC
Labels: bug
