### ISSUE TITLE
[DOC] AuthProvider updated on v4 but not reflected on docs

### ISSUE THREAD

**Issue by iaurg** [refinedev/refine#5529] opened 2024-01-17 16:17 UTC
### Documentation issue

I've come across numerous examples utilizing the AuthProvider typing:

[What is Auth Provider](https://refine.dev/docs/tutorial/understanding-authprovider/index/#what-is-auth-provider)
[Creating a Mock Auth Provider](https://refine.dev/docs/tutorial/understanding-authprovider/create-authprovider/#creating-a-mock-auth-provider)

However, in the migration tutorial, specifically [here](https://refine.dev/docs/migration-guide/auth-provider/#naming-changes), there seems to be a discrepancy. The [migration guide from 3.x to 4.x](https://refine.dev/docs/migration-guide/3x-to-4x/#authprovider) provides different information. When attempting to import:

```js
import type { AuthProvider } from "@refinedev/core";
```

TypeScript returns the following error: '"@refinedev/core"' has no exported member named 'AuthProvider'. Did you mean 'OAuthProvider'?ts(2724)

Upon inspecting the typings inside the core, I found a slight difference from the documentation:

<img width="790" alt="image" src="https://github.com/refinedev/refine/assets/11761170/369b9ce7-da29-4ad0-afa4-db5a00083f21">

Should we update the AuthProvider in examples and code to AuthBindings, or is it necessary to continue using LegacyAuthProvider for now? On examples and documentation.

I'm using the following packages:
```json
...
"dependencies": {
    "@emotion/react": "^11.8.2",
    "@mantine/core": "^5.10.4",
    "@mantine/dates": "^5.10.4",
    "@mantine/form": "^5.10.4",
    "@mantine/hooks": "^5.10.4",
    "@mantine/notifications": "^5.10.4",
    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.46.1",
    "@refinedev/devtools": "^1.1.29",
    "@refinedev/inferencer": "^4.5.16",
    "@refinedev/kbar": "^1.3.5",
    "@refinedev/mantine": "^2.29.1",
    "@refinedev/react-router-v6": "^4.5.5",
    "@refinedev/react-table": "^5.6.5",
    "@refinedev/simple-rest": "^5.0.1",
    "@tabler/icons": "^1.1.0",
    "axios": "^1.6.2",
    "query-string": "^7.1.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.8.1"
  },
  "devDependencies": {
    "@types/node": "^18.16.2",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "typescript": "^4.7.4",
    "vite": "^4.3.1"
  },
  ...
  ```

### Describe the thing to improve

We can update docs and code examples with the new typings from V4

**Comment by arghyapolley** [comment] 2024-01-17 20:19
Need to improve the import statement 
import type { AuthBindings } from "@refinedev/core";
but if we face problem in AuthBindings for direct replacement of AuthProvider, should provide a clear guidance on when to use AuthBindings and when to use AuthProvider depending on the use case.

**Comment by aliemir** [comment] 2024-01-18 05:58
Hello, sorry for the trouble! There's a recent change on these types `AuthBindings` is re-exported as `AuthProvider` for consistency but the docs are unintentionally released early before the actual version release. Check out the PR here https://github.com/refinedev/refine/pull/5503 it will be released in the first week of February. We'll try to revert changes in the docs for now to avoid confusion 😅

**Comment by santubangalore** [comment] 2024-01-23 08:20
So, what should we do? I mean, I am also getting the same error "@refinedev/core"' has no exported member named 'AuthProvider'. Did you mean 'OAuthProvider'?ts

**Comment by BatuhanW** [comment] 2024-01-23 08:44
> So, what should we do? I mean, I am also getting the same error "@refinedev/core"' has no exported member named 'AuthProvider'. Did you mean 'OAuthProvider'?ts

Hello @santubangalore, sorry for the frustration! You can use `AuthBindings` from `@refinedev/core`, instead of `AuthProvider` for now.

**Comment by santubangalore** [comment] 2024-01-24 18:26
Hello @BatuhanW , Thank you that solved this problem. But I am facing another problem of authentication i.e relating to registering new user. Its throwing error "Cannot destructure property 'success' of 'undefined' as it is undefined.".

I am using AuthPage from refine. 

export const Register = () => {
  return <AuthPage type="register" />;
};

any idea what is causing this error?

**Comment by BatuhanW** [comment] 2024-01-25 12:02
Hey @santubangalore you can use our discord channel for this kind of questions, as they are not a bug or issue with Refine itself. https://discord.gg/refine

I also suggest reading our [Authentication Guide](https://refine.dev/docs/guides-concepts/authentication/) to understand concepts.

From the error, I can **guess** that your authProvider's register method doesn't return `{ success: true }`.

**Comment by BatuhanW** [comment] 2024-01-25 12:04
Let me add the related PR here for reference, we'll release it in [February Release Milestone](https://github.com/refinedev/refine/milestone/5).

https://github.com/refinedev/refine/pull/5514

**Comment by niradler** [comment] 2024-02-02 00:43
> I also suggest reading our [Authentication Guide](https://refine.dev/docs/guides-concepts/authentication/) to understand 
@BatuhanW Hi, the examples and the docs both are out of date
>import { Refine, AuthProvider } from "@refinedev/core";

```
  "name": "auth-material-ui",
  "version": "3.25.0",
```

```
  import {
    GitHubBanner,
    Refine,
    AuthProvider, // '"@refinedev/core"' has no exported member named 'AuthProvider'.
    Authenticated,
} from "@refinedev/core";
import {
    ThemedLayoutV2,
    ErrorComponent,
    RefineThemes,
    useNotificationProvider, // '"@refinedev/mui"' has no exported member named 'useNotificationProvider'.
    RefineSnackbarProvider,
    AuthPage,
} from "@refinedev/mui";
```

**Closed** 2024-02-02 13:41 UTC
Labels: documentation
