### ISSUE TITLE
[BUG] table loading state is false during refetching after invalidation

### ISSUE THREAD

**Issue by Yakoot** [refinedev/refine#5090] opened 2023-10-10 14:37 UTC
### Describe the bug

useTable hook returns tableProps.loading, which is true during first loading or pagination changes, but if I go to edit page, change something, save and go back to the table - new data is loading but tableProps.loading is false so there are no loading indicator. 
I have to use something like this to get real loading state
`    const isLoading = tableProps.loading || tableQueryResult.isFetching || tableQueryResult.isRefetching
`

### Steps To Reproduce

1. Go to a table with long data request
2. Open edit page
3. Edit something, save and go back to the table
4. Table doesn't show loading indicator

### Expected behavior

Loading indicator

**Comment by BatuhanW** [comment] 2023-10-10 15:04
Hello @Yakoot, thanks for the issue!

As you mentioned, `loading` is true when we don't have any data initially and loading for the first time. I think your solution looks correct, you can use `isFetching` if you have some different use-cases. Closing the issue as this is an expected behaviour, but feel free to re-open it and/or provide us a minimal reproducible example if your issue is different.

**Closed by BatuhanW** 2023-10-10 15:04 UTC
Labels: bug

**Comment by mabezdek** [comment] 2025-02-14 21:28
Wouldn’t it be more appropriate in such a case to export the loading state within tableProps based on isFetching?

We were also looking for the reason why the spinner does not appear when navigating back to the route, and we only found the answer here.

In the case of AntDesign, there is even a noticeable blocking of the entire table rendering. Setting the loadingState according to isFetching has a positive impact on UX.
