### ISSUE TITLE
[BUG] OnClick action from DeleteButton should not trigger confirmation pop up, when disabled property is set

### ISSUE THREAD

**Issue by joanaavelar** [refinedev/refine#3605] opened 2023-02-13 18:17 UTC
### Describe the bug

When setting disabled property on DeleteButton component from refine, although styling reflecting a disabled button, the click action is possible. It shows a confirmation modal.

### Steps To Reproduce

1- Go to [this](https://codesandbox.io/s/dazzling-feather-bujyiv) sample
2- On tableColumns whose _dataIndex="actions"_ add the following   **<DeleteButton disabled/>** as sibbling of _EditButton_
![image](https://user-images.githubusercontent.com/11629784/218538842-ae5367df-94a1-4bee-b88d-871b3a42d1ca.png)
3- See that the delete button look and feel changed (from active delete button to a disabled one)
4- Click on the delete button 
5- See that a confirm delete modal is shown
![image](https://user-images.githubusercontent.com/11629784/218539453-69155104-8bc0-4a01-9309-ea46dce84c98.png)

### Expected behavior

Disabled property should prevent the confirmation modal to be shown.

**Comment by aliemir** [comment] 2023-02-13 18:20
Hey @joanaavelar, sorry for the issue 🙏 Looks like a regression, we had this issue in some earlier versions but had it fixed. Probably missed something during the Ant Design version bump 🤦 We'll check the issue and deploy a fix soon 🚀 Just to make sure, which version of `@pankod/refine-antd` you're using?

**Comment by joanaavelar** [comment] 2023-02-13 19:08
Hi @aliemir , the sample that I've shared on the bug is from the refine examples section.
Please see the versions on the below image:
![image](https://user-images.githubusercontent.com/11629784/218551137-9777a562-ad46-4de4-8f96-465235e59104.png)

**Comment by aliemir** [comment] 2023-02-13 19:57
Just identified the issue and resolved in my local tests. Opened up a PR here https://github.com/refinedev/refine/pull/3606

It will be merged and released soon, sorry again for the issue 🙏

**Comment by joanaavelar** [comment] 2023-02-13 21:58
no problem. Thanks for the quick reply and fix :)

**Closed** 2023-02-14 06:53 UTC
Labels: bug
