### ISSUE TITLE
[BUG] [refine-remix is not a valid preset] pnpm create refine-app@latest won't create Refine + Remixjs + Ant Design starter template

### ISSUE THREAD

**Issue by jackytank** [refinedev/refine#6410] opened 2024-10-15 18:36 UTC
### Describe the bug

I follow this Refine guide to initiate my Refine + Remix Router + Ant Design starter project (https://refine.dev/docs/routing/integrations/remix/#usage)

When using this command
```bash
pnpm create refine-app@latest -- -o refine-remix my-refine-remix-app
```

I receive this output which say __refine-remix is not a valid preset__
```bash
 __________________________________________
/ They asked for a robust B2B solution. We \
\ heard 'time to shine with Refine'!       /
 ------------------------------------------
        \   ^__^
            ■-■¬\_______
            (__)\       )\/\
                ||----w |
                ||     ||
✔ Downloaded remote source successfully.
refine-remix is not a valid preset.
? Choose a project template ...
> Vite Creates a refine React Vite project.
  Next.js Creates a refine Next.js project with SSR support.
```

I'm desperate for a Refine + Remix + Ant Design + Vite combo as of Nextjs 14+ App Router and Turpopack was too painfully slow even with turbo turned on
```bash
npm run dev --turbo
```

### Steps To Reproduce

1. Type this to initiate project ```pnpm create refine-app@latest -- -o refine-remix my-refine-remix-app```
2. Observe the terminal output that say
```sh
 __________________________________________
/ They asked for a robust B2B solution. We \
\ heard 'time to shine with Refine'!       /
 ------------------------------------------
        \   ^__^
            ■-■¬\_______
            (__)\       )\/\
                ||----w |
                ||     ||
✔ Downloaded remote source successfully.
refine-remix is not a valid preset.
? Choose a project template ...
> Vite Creates a refine React Vite project.
  Next.js Creates a refine Next.js project with SSR support.
```

### Expected behavior

a starter project Refine + Vite + Remix + Ant Design will be created successfully with various option for auth/no-auth, with sample pages/no-pages, data provider options

### Packages

refine-app@latest

### Additional Context

Love your great work with Refine.dev, I'm now introduce refine framework to everyone at my company for internal tools needs

**Comment by BatuhanW** [comment] 2024-10-16 07:48
Hello @jackytank, we've removed remix from the CLI but it seems we didn't update the documentation.

You can use the following command to create your remix antd application, we'll update the docs soon.

`npm create refine-app@latest -- --example with-remix-antd`

**Comment by jackytank** [comment] 2024-10-16 08:49
Noooo.... don't remove Remix please, Nextjs 14+ App Router Turbo compile so horrendously slow compare to Vite, but normal Vite React is not enough for my company project

**Comment by jackytank** [comment] 2024-10-16 08:52
after run this command to create remix + antd project
```sh
npm create refine-app@latest -- --example with-remix-antd
```

It is having some bugs and errors

![image](https://github.com/user-attachments/assets/84a38b8a-c2a6-43aa-9603-ebc31d91e5d0)

**Comment by alicanerdurmaz** [comment] 2024-10-16 08:58
> after run this command to create remix + antd project
> 
> ```shell
> npm create refine-app@latest -- --example with-remix-antd
> ```
> 
> It is having some bugs and errors
> 
> ![image](https://private-user-images.githubusercontent.com/52403567/376968677-84a38b8a-c2a6-43aa-9603-ebc31d91e5d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjkxMTUsIm5iZiI6MTcyOTA2ODgxNSwicGF0aCI6Ii81MjQwMzU2Ny8zNzY5Njg2NzctODRhMzhiOGEtYzJhNi00M2FhLTk2MDMtZWJjMzFkOTFlNWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA4NTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzc5YTM3MzMzZjAwZTljZTU1NzFlYjljMjQ0MThmNDAyYjFhNTYwM2JkZWQxNDYwYzQ0MGJiNjlkZmI4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L2CRZCwtA8ZJGALfdBCxga7PGJuJhFKxucjRAyrfdck)

Hi @jackytank, I couldn't reproduce the issue. What command did you use to start the project?

**Comment by BatuhanW** [comment] 2024-10-16 09:22
> Noooo.... don't remove Remix please, Nextjs 14+ App Router Turbo compile so horrendously slow compare to Vite, but normal Vite React is not enough for my company project

We didn't remove Remix support, but we only removed it from the CLI boilerplate generate, because it adds a lot of maintenance overhead and not so different from our examples already.

**Comment by jackytank** [comment] 2024-10-16 09:53
> Hi @jackytank, I couldn't reproduce the issue. What command did you use to start the project?

Oh you mean running the project from this command? ```npm create refine-app@latest -- --example with-remix-antd```

My PC environment:
npm 10.9.0
node v21.1.0

Steps:
1. Using the template generated from ```npm create refine-app@latest -- --example with-remix-antd```, 
2. Run it up using ```npm run dev```
3. Click the posts page in the left sidebar
![image](https://github.com/user-attachments/assets/331bf914-6a74-4e62-9c86-df5eb31df341)
4. Error will be shown
![image](https://github.com/user-attachments/assets/f8d8ce91-52d7-48f3-bc2e-2fda22e87f99)

Relevant/helpful screenshots:
1. Terminal
![image](https://github.com/user-attachments/assets/ae0dc8f0-d803-442f-adc2-813df4d5ff2b)
2. Its package.json 
![image](https://github.com/user-attachments/assets/ba56f6a4-ba43-4022-aff0-f20dd5070850)

**Comment by BatuhanW** [comment] 2024-10-16 13:01
Hello @jackytank, in order to run NextJS app with turbo, you need to add additional `--` before `--turbo`.

`npm run dev -- --turbo`, if you don't add `--`, additional parameters won't be passed.

On Remix, can you try with Node 20 stable version? We didn't test with Node 21 and it failed to install on my mac.

Finally, it seems you have random ports for your application, is it expected? Normally port would be 3000 for remix apps. Wanted to check if anything is off with that.

**Comment by jackytank** [comment] 2024-10-16 13:37
> Sorry @jackytank I couldn't reproduce the problem. Everything works as expected on my PC.
> 
> Maybe something is wrong with your `node` setup but I don't know what it is. My setup is like this:
> 
> ```
> ## System:
>  - OS: macOS 14.5
>  - CPU: (10) arm64 Apple M2 Pro
> ## Binaries:
>  - Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
>  - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
>  - npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
> ## Browsers:
>  - Chrome: 129.0.6668.101
>  - Safari: 17.5
> ```
> 
> Can you change your package.json's dev script to this and try again? I will disable Refine CLI and it will use `remix` directly.
> 
> ```json
> "dev": "remix dev"
> ```

Hi the issue I said earlier when trying this template
```sh
npm create refine-app@latest -- --example with-remix-antd
```

My company PC have node v21.1.0 installed and also we have firewall in company Ethernet so maybe some nodejs packages were being block traffic by our firewall rules when ```npm i```

After trying running again ```npm create refine-app@latest -- --example with-remix-antd``` on my personal Laptop with below environment and with both "refine dev" and "remix dev"

npm 10.9.0
node v20.16.0

The template work perfectly without earlier error I said

**Comment by jackytank** [comment] 2024-10-16 13:48
> Hello @jackytank, in order to run NextJS app with turbo, you need to add additional `--` before `--turbo`.
> 
> `npm run dev -- --turbo`, if you don't add `--`, additional parameters won't be passed. Not %100 sure if that's the case for windows as well.
> 
> On Remix, can you try with Node 20 stable version? We didn't test with Node 21 and it failed to install on my mac.
> 
> Update: I installed Node 21 and couldn't reproduce the issue.
> 
> ~Finally, it seems you have random ports for your application, is it expected? Normally port would be 3000 for remix apps. Wanted to check if anything is off with that.~ Nvm. Just realized it allocates a random port if 3000 isn't available.

Hi I had try again with ```npm run dev -- --turbo``` and with node v20.16.0 on my personal Laptop
the slow NextJS compile time still there, and after done some research before this issue maybe due to NextJS poor compiling performance (not Refine)

**Comment by BatuhanW** [comment] 2024-10-17 06:28
Hey @jackytank closing the issue then.

**Closed by BatuhanW** 2024-10-17 06:28 UTC
Labels: bug
