### ISSUE TITLE
[BUG] refinedev/antd components not following configured theme

### ISSUE THREAD

**Issue by annschulte** [refinedev/refine#4998] opened 2023-09-22 18:32 UTC
### Describe the bug

**Packages**
next: 13.5.2
@refinedev/antd: 5.36.2
@refinedev/core: 4.42.0
antd: 5.9.2

When using a custom theme in the <ConfigProvider /> all the refine components are not switching themes. 

### Steps To Reproduce

1. Spin up an app with the latest version of next, antd, and refine
2. Render a refine antd component with the default dark algorithm configured in the <ConfigProvider />
3. Refine component theming is incorrect

### Expected behavior

The theming of the components should change.

### Screenshot

<img width="1169" alt="Screenshot 2023-09-22 at 1 27 00 PM" src="https://github.com/refinedev/refine/assets/67656273/1098179b-dfd2-4840-ab86-3031665d83ad">

**Comment by alicanerdurmaz** [comment] 2023-09-25 07:09
I created a new refine application with the following options, but I could not see any problem. What am I missing?

```bash
 Downloaded remote source successfully.
✔ Choose a project template · refine-vite
✔ What would you like to name your project?: · tangy-beers-try
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · antd
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · none
✔ Do you need i18n (Internationalization) support?: · i18n-antd
✔ Choose a package manager: · npm
✔ Mind sharing your email? (We reach out to developers for free priority support, events, and SWAG kits. We never spam.) ·
```
![localhost_5174_blog-posts_pageSize=10 current=1](https://github.com/refinedev/refine/assets/23058882/e661fd47-9a30-420f-afbf-d45a310d1963)

**Comment by annschulte** [comment] 2023-09-25 15:33
Hi @alicanerdurmaz I was using next as the framework and it seems to be related to that for me not Vite. Thanks!

**Comment by aliemir** [comment] 2023-09-25 15:39
Hey @annschulte, can you check this doc from Ant Design, https://ant.design/docs/react/use-with-next#using-pages-router I'm thinking this issue is related to the missing configuration in `create-refine-app`'s generated projects with Next.js and Ant Design 🤔

**Comment by annschulte** [comment] 2023-09-25 15:53
> Hey @annschulte, can you check this doc from Ant Design, https://ant.design/docs/react/use-with-next#using-pages-router I'm thinking this issue is related to the missing configuration in `create-refine-app`'s generated projects with Next.js and Ant Design 🤔

Hmm, that is not fixing the issue unfortunately.

**Comment by annschulte** [comment] 2023-09-26 14:23
@aliemir @alicanerdurmaz any updates here?

**Comment by omeraplak** [comment] 2023-10-03 15:01
Hey, we haven't had a chance to address this topic yet. Is there anyone from the community who'd like to take it on?

**Comment by aliemir** [comment] 2023-10-11 12:33
Hey @annschulte, 

This issue was related with the Ant Design's CSS in JS library not properly passing the tokens/theme to the compiled components. In your case, we're exporting components using Ant Design from `@refinedev/antd` and `@refinedev/inferencer`.

I was able to reproduce the issue and had a fix using a simple change in `next.config.js`. 

If you add `@refinedev/antd` and `@refinedev/inferencer` (if you're using it of course) to `transpilePackages` array, the theme will work as expected.

```js
/** @type {import('next').NextConfig} */
module.exports = {
  transpilePackages: [
    "@refinedev/antd",
    "@refinedev/inferencer"
  ],
};
```

Let us know if this fixes your issue as well @annschulte  🙏

**Comment by aliemir** [comment] 2023-10-15 20:18
Closing this issue because of the shared solution above. Do not hesitate to send an update if there's any update about the issue here.

**Closed by aliemir** 2023-10-15 20:18 UTC
Labels: bug, hacktoberfest
