### ISSUE TITLE
[BUG] Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by gokanlam** [refinedev/refine#5279] opened 2023-11-19 16:32 UTC
### Describe the bug

After creating a new application with the `npm create refine-app@latest testapp` command, the application does not start with the `nmp run dev` command and the following error occurs:

```
> testapp@0.1.0 refine
> refine

/home/user/testapp/node_modules/node-emoji/lib/index.cjs:47
var import_is2 = __toESM(require("@sindresorhus/is"), 1);
                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/testapp/node_modules/@sindresorhus/is/dist/index.js from /home/user/testapp/node_modules/node-emoji/lib/index.cjs not supported.
Instead change the require of index.js in /home/user/testapp/node_modules/node-emoji/lib/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/user/testapp/node_modules/node-emoji/lib/index.cjs:47:26)
    at Object.<anonymous> (/home/user/testapp/node_modules/marked-terminal/index.cjs:10:13)
    at Object.<anonymous> (/home/user/testapp/node_modules/@refinedev/cli/dist/cli.js:25:1400) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Steps To Reproduce

1. `npm create refine-app@latest testapp`
```
✔ Choose a project template · refine-vite
✔ What would you like to name your project?: · testapp
✔ Choose your backend service to connect: · data-provider-strapi-v4
✔ Do you want to use a UI Framework?: · antd
✔ Do you want to add example pages?: · no
✔ Do you need i18n (Internationalization) support?: · no
```
2. `cd testapp`
3. `npm run dev`

### Expected behavior

Run normally.

### Additional Context

OS: ubuntu 22.04 LTS
Node: v20.9.0
NPM: v10.1.0
create-refine-app: v1.12.1

**Comment by romainds-tech** [comment] 2023-11-19 18:26
I have the same error, impossible to create a project

**Comment by 3MenWalking** [comment] 2023-11-19 19:47
Sam exact issue here with a totally fresh install of all the toolchain on a Mac(NVM/NPM/Node, etc ).  Impossible to continue.

**Comment by medrishya** [comment] 2023-11-20 05:50
I too have got the same issue, impossible to run a new latest refine project.

**Comment by aliemir** [comment] 2023-11-20 06:42
Sorry for the issue! 🙏  We've just opened a PR to fix it. It will be released as soon as workflows are complete! 🚀

**Comment by ernestasgobionis** [comment] 2023-11-20 15:21
Just created a new project which includes the latest update to `node-emoji: 2.1.0`, and I'm getting the exact same error

**Comment by romainds-tech** [comment] 2023-11-20 16:00
I'm getting the exact same error too with a new project I use this command :
`npm create refine-app@latest`

**Comment by BatuhanW** [comment] 2023-11-20 16:11
Hello folks, using the command `npm create refine-app@latest testapp`, couldn't reproduce the problem, as you can see in the screenshot, it works as expected. I can see the welcome page as expected, could you double-check your configuration or provide a minimal reproducible example if possible? 


<img width="1053" alt="Screenshot 2023-11-20 at 19 09 32" src="https://github.com/refinedev/refine/assets/16444991/1c6a98b0-3063-4643-b057-7289d41e412a">

![Screenshot 2023-11-20 at 19 10 58](https://github.com/refinedev/refine/assets/16444991/cd1d752b-6c06-463d-a02f-982726f291c2)

**Comment by ernestasgobionis** [comment] 2023-11-20 16:32
Here you go:[repo](https://github.com/ernestasgobionis/refine-repro/tree/main)

Also note I found that when I run `npm ls node-emoji`, I get this output:

```
refine-repro@0.1.0 /Users/ex/Desktop/refine-admin/refine-repro
└─┬ @refinedev/cli@2.16.17
  ├─┬ marked-terminal@6.1.0
  │ └── node-emoji@2.1.1
  └── node-emoji@2.1.0
```

Looks like 2.1.1 is coming from `marked-terminal@6.1.0`

**Comment by romainds-tech** [comment] 2023-11-20 16:40
Hi @BatuhanW,  I use this configuration

![CleanShot 2023-11-20 at 17 36 17@2x](https://github.com/refinedev/refine/assets/79503939/8034db4e-6c37-4912-9d28-65d412608536)

then when I use `pnpm dev` I got this error 

![CleanShot 2023-11-20 at 17 37 11@2x](https://github.com/refinedev/refine/assets/79503939/bc1ea916-5a83-46d3-a7f9-107ea43504c9)

**Comment by BatuhanW** [comment] 2023-11-20 16:43
Hello folks, it seems we still have this issue with `yarn` and `pnpm` package managers. As a temporary workaround, you can use `npm` to install dependencies.

Also we've noticed that a new version is released 15 minutes ago, we'll upgrade to use it.

https://github.com/omnidan/node-emoji/issues/153

**Comment by 3MenWalking** [comment] 2023-11-20 16:56
Can confirm using npm with the latest now works.  Thanks!

**Comment by JoshuaKGoldberg** [comment] 2023-11-20 22:05
Hiyall - this was me, sorry about that. I'd neglected to fully test a [tooling upgrade for `node-emoji`](https://github.com/omnidan/node-emoji/pull/142) that bumped dependencies, enabled auto-updates via Renovate for others, and didn't add an end-to-end test that CommonJS consumers wouldn't be broken.

[node-emoji@2.1.3](https://www.npmjs.com/package/node-emoji?activeTab=versions) is published now and should be working for CommonJS consumers again. Please do let us know in https://github.com/omnidan/node-emoji if anything else gets / is broken!

Also, copying here in case it's useful for this or similar situations: workaround that should work across package managers in the case of a dependency breaking, including a deep dependency-of-a-dependency, is using an `overrides`/`resolutions` style pin.
* npm: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
* pnpm: https://pnpm.io/package_json#pnpmoverrides (secondary: https://pnpm.io/package_json#resolutions)
* Yarn classic: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
* Yarn berry/2+: https://yarnpkg.com/cli/set/resolution

Cheers! 👋

**Closed** 2023-11-20 22:22 UTC
Labels: bug

**Comment by BatuhanW** [comment] 2023-11-20 23:34
Thanks a lot @JoshuaKGoldberg, tested with `pnpm`, and I can confirm, it works as expected!
