### ISSUE TITLE
[BUG] i get error with "@refinedev/mui": "^5.19.0",

### ISSUE THREAD

**Issue by unrealphong** [refinedev/refine#6155] opened 2024-07-18 16:35 UTC
### Describe the bug

use notificationProvider={useNotificationProvider} error

### Steps To Reproduce

use notificationProvider={useNotificationProvider} error

### Expected behavior

null

### Packages

@refinedev/mui

**Comment by aliemir** [comment] 2024-07-18 22:25
Hey @unrealphong, this is now what we expect when users report a bug. A proper bug report is crucial for us to understand issues and resolve them. A well-documented issue helps contributors find and fix issues more efficiently, making the project better for everyone. 🏖️ 

The issue is probably related with the missing `<SnackbarProvider />` wrapper around `<Refine />` component. Please try to wrap your `<Refine />` component with `<SnackbarProvider />` from `@refinedev/mui`. 

I'm closing this issue for now. If this does not resolve the issue, please do not hesitate to reopen with more information on the issue and a minimal repro for us to work with. 🙏

**Closed by aliemir** 2024-07-18 22:25 UTC
Labels: bug
