### ISSUE TITLE
[BUG] MUI useDataGrid's dataGridProps type not compatible with DataGridPro

### ISSUE THREAD

**Issue by jamesdh** [refinedev/refine#5997] opened 2024-05-28 17:11 UTC
### Describe the bug

Upon trying to upgrade from MUI DataGrid to DataGridPro, I'm getting the following TS errors: 

```
TS2322: Type ... is not assignable to type DataGridProProps<any>
Types of property onFilterModelChange are incompatible.
Types of parameters details and details are incompatible.
Types of property reason are incompatible.
```

### Steps To Reproduce

Create an extremely basic component w/ useDataGrid: 

```typescript
import React from 'react';
import {List, useDataGrid} from '@refinedev/mui';
import {DataGridPro} from '@mui/x-data-grid-pro';

const ListPage = () => {
  const { dataGridProps } = useDataGrid<any>({})
  return (
    <List>
       <DataGridPro {...dataGridProps} columns={[]} />
    </List>
  )
}
```

### Expected behavior

The `dataGridProps` type returned from `useDataGrid` will also be compatible with `DataGridPro`.

### Packages

- "@refinedev/core": "4.49.2"
- "@refinedev/mui": "5.15.1"
- "@mui/material": "5.15.8"
- "@mui/x-data-grid-pro": "7.5.1"

**Comment by jamesdh** [comment] 2024-05-29 16:23
Downgrading `@mui/x-data-grid-pro` to 6.20.0 helped resolve this. It's a bit odd, as prior to upgrading to the Pro license, the regular `@mui/x-data-grid` was working fine w/ 7.5.1

**Comment by aliemir** [comment] 2024-05-30 08:33
Hey @jamesdh sorry for the issue! I've investigated this a bit. Looks like this is just a type issue and caused by a faulty type from our `useDataGrid` hooks return type. We have `onFilterModelChange` as `DataGridProps["onFilterModelChange"]` in the return type (the function has two arguments `model` and `details`) but we're only using the `model` and doesn't even have `details` in the implementation 😅 

We can update the return type to reflect our implementation (which still satisfies the `onFilterModelChange` prop of DataGrid components) and get rid of this error easily. 

Here's the part defining the return type of the hook:

https://github.com/refinedev/refine/blob/77df5be781497681b1ef2718538d76ad41d76901/packages/mui/src/hooks/useDataGrid/index.ts#L33-L53

Instead of inferring it directly from the `DataGridProps`, we can define `onFilterModelChange` as:

```ts
onFilterModelChange: (model: GridFilterModel) => void;
```

If you want to contribute to Refine and help us fix the issue, check out the [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing/#ways-to-contribute) to get started!

**Comment by bhargavpshah98** [comment] 2024-06-09 07:05
Hello @jamesdh @aliemir , I would like to contribute for working on this issue. Can you please assign it to me?

**Comment by jamesdh** [comment] 2024-06-09 15:06
@bhargavpshah98 absolutely! Feel free to submit a PR for it!

**Comment by aliemir** [comment] 2024-06-10 16:11
Hey @bhargavpshah98, assigned the issue! I think my comment above will be enough to get the task done but let us know if you need any help! 🙏 

@jamesdh, did you had a chance to check my comment above about the solution, do you need any workaround for now, or does just casting the proper types resolves the issue in your codebase? 🙏

**Comment by bhargavpshah98** [comment] 2024-06-10 18:23
Hello, @aliemir , Thank you for assigning the task. Yeah, that sounds good. I will reach out if I need any help or guidance.

**Comment by bhargavpshah98** [comment] 2024-06-13 20:50
Hello @aliemir @jamesdh , I need some help regarding testing of the code and the changes I found in the codebase. Let me know the best way to connect with you.

**Comment by jamesdh** [comment] 2024-06-15 13:59
@bhargavpshah98 the easiest way is to create a draft PR and ask for feedback on your changes directly.

**Comment by Sergio16T** [comment] 2024-07-11 21:16
Hello @aliemir.  Is this issue still open? Looks as though the fix didn't make it to PR.

**Comment by aliemir** [comment] 2024-07-16 06:12
Hey @Sergio16T, issue is still open and available 🚀 I can assign it to you if you're willing to work on it, let me know if any help is needed 🙏

**Comment by Sergio16T** [comment] 2024-07-17 18:12
@aliemir Thank you! That sounds good. I'm attempting to replicate the error by editing the example for material-ui useDataGrid in list and I'm not getting any typescript errors. 

At the following: 
https://github.com/refinedev/refine/blob/efccf47e97d0bc1b1986cd95d163ae5a10d24ea1/examples/base-material-ui/src/pages/posts/list.tsx#L6 

I imported  x-data-grid-pro `import {DataGridPro} from '@mui/x-data-grid-pro';`. 

What am I missing to replicate?

**Comment by Sergio16T** [comment] 2024-07-17 19:28
@aliemir PR is ready for review.

**Closed** 2024-08-05 10:32 UTC
Labels: bug, good first issue
