### ISSUE TITLE
[BUG] Binding of "useselect" in filters with Antd works incorrectly

### ISSUE THREAD

**Issue by ruben0909** [refinedev/refine#4863] opened 2023-08-24 21:12 UTC
### Describe the bug

I found a small bug in the application of the querystring filters to the "select" in the case of using "Antd" with Refine.dev

Example web with bug:
https://example.admin.refine.dev/orders?pageSize=10&current=1&filters[0][field]=user.id&filters[0][operator]=eq&filters[0][value]=1

NOTE: This bug does not occur in MUI.

Example web without bug:
https://example.mui.admin.refine.dev/orders?pageSize=10&current=1&filters[0][field]=store.id&filters[0][operator]=eq&filters[0][value]=1

Thank you for your wonderful project

### Steps To Reproduce

1. Apply a select filter on a web page with refine and Antd
2. Reload page (f5) or copy to another tab/browser
3. The binding of the query filter is done incorrectly by setting the option to value instead of the text in the filter.
You will see "1" in the select instead of "Walter Ridge".

### Expected behavior

The same text should be displayed in the select when filtering for the first time, if the page is reloaded, opened in another tab or the url is shared.

### Screenshot

Expected behaviour:
![image](https://github.com/refinedev/refine/assets/1110434/bc588ba5-c21c-4d4d-8f12-5bdf49e6a44e)

Wrong/Real behaviour:

![image](https://github.com/refinedev/refine/assets/1110434/6f5e26df-0f2f-428c-84da-2d500606bedd)

### Desktop

- Device: PC
- OS: Windows
- Browser: Chrome
- Version:- 116
- Used Official Sample Fine Foods of Antd Refine.dev

**Comment by BatuhanW** [comment] 2023-08-25 08:44
Hello @ruben0909 thanks for the kind words and the detailed issue! We've added it to our backlog, however if you want to work on this issue and make a contribution, feel free to do so!

**Comment by ShivangRawat30** [comment] 2023-08-29 10:55
@BatuhanW I would like to work on this issue.

**Comment by BatuhanW** [comment] 2023-08-29 11:00
Hello @ShivangRawat30, great! Assigning this issue to you, looking forward!

**Comment by salihozdemir** [comment] 2023-09-11 10:18
Hey @ruben0909,

This problem was caused by a type mismatch. The value we infer from the URL is string, but the `<Select>` component holds a number value, so there was such a problem. You can see the solution in the PR I opened.

**Closed** 2023-09-11 13:04 UTC
Labels: bug

**Comment by ruben0909** [comment] 2023-09-11 17:39
Thank you so much.

**Comment by bartbrinkman** [comment] 2024-12-17 20:30
This was still very much an issue for me, I never could get conditional rendering, initialValues, defaultValue or otherwise to work. I ended simply updating the values themselves:

```js
if (selectProps.options) {
    selectProps.options.map((option) => {
      option.value = option.value ? option.value.toString() : option.value;
      return option;
    });
}
```
