### ISSUE TITLE
useForm invalidates: false does still result in refetch after submit

### ISSUE THREAD

**Issue by JEkedorff** [refinedev/refine#4856] opened 2023-08-23 20:51 UTC
### Describe the bug

Using below code to handle a form submission. After successful submission, the form query make a refetche even though **invalidates: false** is set (same behaviour is seen with invalidates: ["list"] and any other value)

We are using a custom GraphQL live provider using Apollo client.

Every mutation return the created/updated object it our application, so we want this to update the query data directly and skip this unwanted refetch.

### Steps To Reproduce

1. Add a form using useForm hook:

```
const formProps = useForm<ICompany>({
        refineCoreProps: {
            meta: {
                fields: companyFields,
                environmentId: environment?.id
            },
            action: "edit",
            resource: resourceName,
            id: id,
            redirect: false,
            mutationMode: "pessimistic",
            invalidates: false as any
        },
        mode: "onChange",
        defaultValues: { id: id, ...defaultValues },
        resolver: ajvResolver(schema, undefined, { language: currentLocale })
    });
```

2. Submit form
3. See that query data is refetched in DevTools, after mutation is complete.

### Expected behavior

In step 3, no refetch was expected after submission success.

### Desktop

Windows 11, Chrome
Refine v4

**Comment by BatuhanW** [comment] 2023-08-24 07:11
Hello @JEkedorff, I guess you have `liveMode: auto`, which invalidates query when it receives live event. You can change it to manual if you want to disable refetching.

We want to improve this flow and update query cache instead of triggering refetch in the future.

**Comment by BatuhanW** [comment] 2023-10-02 07:56
Hello again @JEkedorff,

We've discussed this one internally with core team and agreed that there is no consistent way to update query cache with live event data. We could append it to the end of the list but for example, your result might be in the middle of the list (you may have some server side custom order). So we can't guess which position to insert data coming from live provider.

I agree that passing `invalidates: false` gives a feeling that this shouldn't be invalidated, but it only prevents invalidate in `useForm` context.

These invalidation happens at the other side of the stack in the live provider.

We are creating some feature requests internally to explore options:
- Maybe disable invalidates on resource level.
- Also provide users a way to update their cache as they wish by giving user query cache and live provider event. So users can choose how to handle it.


Closing the issue as it's not a bug, we'll release improvements as a feature in the coming weeks.

**Closed by BatuhanW** 2023-10-02 07:56 UTC
Labels: bug
