### ISSUE TITLE
[BUG] Antd notificationProvider notifications don't follow theme style

### ISSUE THREAD

**Issue by wxkk** [refinedev/refine#4654] opened 2023-07-11 00:54 UTC
### Describe the bug

Notifications have a white background even tho the dark theme is set.

### Steps To Reproduce

1. Go to [customization-theme-antd](https://codesandbox.io/embed/github/refinedev/refine/tree/next/examples/) example.
2. Set the dark theme by clicking the moon icon.
3. Click the edit button of any post, then click Save.
4. Notice how the "Successfully updated post" notification is white even tho the dark theme is set.

### Expected behavior

Notifications should follow the theme style, like they do in the [ant design](https://ant.design/components/notification?theme=dark) examples.

### Screenshot

![](https://i.imgur.com/65uMvXJ.png)

**Comment by BatuhanW** [comment] 2023-07-13 08:15
Hello @wxkk thanks for the issue! We'll check and get back to you soon.

**Comment by salihozdemir** [comment] 2023-07-27 06:39
Hi @wxkk,

We'll fix it in the next release. If you want to open a PR, you can update the [`notificationProvider`](https://github.com/refinedev/refine/blob/next/packages/antd/src/providers/notificationProvider/index.tsx) from `@refinedev/antd` package. Currently, it's using the `notification` static method from `antd` package, You can change implementation like antd mentioned in their docs: https://ant.design/components/notification#components-notification-demo-hooks which is using `notification.useNotification` hook.

**Comment by MahirMahdi** [comment] 2023-08-08 17:07
> Hi @wxkk,
> 
> We'll fix it in the next release. If you want to open a PR, you can update the [`notificationProvider`](https://github.com/refinedev/refine/blob/next/packages/antd/src/providers/notificationProvider/index.tsx) from `@refinedev/antd` package. Currently, it's using the `notification` static method from `antd` package, You can change implementation like antd mentioned in their docs: https://ant.design/components/notification#components-notification-demo-hooks which is using `notification.useNotification` hook.

If it's still open I would like to work on it.

**Comment by MahirMahdi** [comment] 2023-08-24 02:57
Yes, I am. I would like to work on it.😀

**Comment by MahirMahdi** [comment] 2023-08-24 02:58
Hey @BatuhanW. Yes, I would like to work on it.😀

**Comment by BatuhanW** [comment] 2023-08-24 06:42
@MahirMahdi Assigned to you. 👐🏼

**Comment by MahirMahdi** [comment] 2023-08-30 03:51
But we can't use `notifcation.useNotification` hook in the **[`notificationProvider`](https://github.com/refinedev/refine/blob/next/packages/antd/src/providers/notificationProvider/index.tsx)**. So how can we approach this problem?

**Comment by omeraplak** [comment] 2023-09-02 02:06
> We can't use `notifcation.useNotification` hook in the **[`notificationProvider`](https://github.com/refinedev/refine/blob/next/packages/antd/src/providers/notificationProvider/index.tsx)**. So how can we approach this problem?

Hey @MahirMahdi -- There's a similar usage in our MUI package, you can take a look. I hope it helps. https://github.com/refinedev/refine/blob/next/packages/mui/src/providers/notificationProvider/index.tsx#L13

**Comment by MahirMahdi** [comment] 2023-09-02 03:28
Hey @omeraplak thanks. I used the same approach but it shows this error

![Screenshot 2023-09-02 092317](https://github.com/refinedev/refine/assets/66949598/5dff2e81-fc33-4c19-8c7a-0f976cc40088)
![Screenshot 2023-09-02 092630](https://github.com/refinedev/refine/assets/66949598/57dd3346-55b4-4d69-8ef1-5838c9979798)

**Comment by omeraplak** [comment] 2023-09-02 03:40
I'm not sure, but I found these issues when I searched for the error. They might help:

[Issue #34823 on ant-design](https://github.com/ant-design/ant-design/issues/34823)
[Issue #39592 on ant-design](https://github.com/ant-design/ant-design/issues/39592)

**Comment by MahirMahdi** [comment] 2023-09-02 03:44
I found the 2nd one xD but trying to figure out how can I pass the contextHolder.

**Comment by omeraplak** [comment] 2023-09-02 03:59
Although I'm not entirely sure again, have you tried using the "notification.success" and "notification.error" static methods? Aren't they working?

I believe there's no way for us to add the contextHolder from our antd package, we should have our users implement it. However, this would lead to a breaking change. It's a bit of a frustrating situation :)

**Comment by MahirMahdi** [comment] 2023-09-02 04:24
Yes, the static methods work fine but the issue is they can't access the context. :)

And yes you're right there's no way to add the contextHolder from the antd package. It is :).

**Comment by MahirMahdi** [comment] 2023-09-05 12:01
Hey @omeraplak, hope you are doing great. 

Found a way to access context without passing the `contextHolder`. All users will have to do is import `App` package from _`antd`_  and wrap it around `Refine` like this. 
![Screenshot 2023-09-05 175155](https://github.com/refinedev/refine/assets/66949598/ee05e036-93b4-4d0f-92a3-e07bb4cb7c99)
![Screenshot 2023-09-05 175417](https://github.com/refinedev/refine/assets/66949598/14fd831b-3971-4043-9f47-181ef41fec65)

**Closed** 2023-10-10 07:43 UTC
Labels: bug
