### ISSUE TITLE
[BUG] Cannot use react-hook-form Controller with Refine's useForm

### ISSUE THREAD

**Issue by ritute** [refinedev/refine#6139] opened 2024-07-14 21:11 UTC
### Describe the bug

I'm following the example for Material UI on this page: https://refine.dev/docs/packages/react-hook-form/introduction/#usage

My imports are:

```
import { useForm } from "@refinedev/react-hook-form";
import { Controller } from "react-hook-form";
```

The problem is that it looks we have to use the Edit component from Material UI in order to use Controller, otherwise I get the error:

`React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'subscribe')`

When I wrap my form within the Edit component, this error goes away, but I don't want to use Edit from material UI for my form. Is there a way around this? I'm currently having to use register instead, but I need to use some Material components like Autocomplete.

### Steps To Reproduce

1. Follow the steps in this documentation for Material UI: https://refine.dev/docs/packages/react-hook-form/introduction/#usage
2. Remove the Edit component (don't wrap form with it)

### Expected behavior

Shouldn't require the Edit component in order to use Controller in my form.

### Packages

- react-hook-form: "7.30.0"
- @refinedev/react-hook-form: "^4.8.20"

**Comment by aliemir** [comment] 2024-07-16 14:11
Hey @ritute, using a base Refine + Material UI + React Hook Form setup, I've followed the steps to repro the issue. Just copy-pasted the full Material UI code block and removed the `<Edit />` component but could not reproduce. Can you try to share the broken code from your source or provide a minimal repro? 🙏

**Comment by ritute** [comment] 2024-07-17 19:58
> https://refine.dev/docs/packages/react-hook-form/introduction/#usage

Hmm, okay I just started with a base [sandbox](https://codesandbox.io/p/devbox/gallant-glade-ppvk2d?workspaceId=93d99ed5-22b5-475b-8fd2-2e9babd4a6cd&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyq9c8k500073b6mg82j7mr6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyq9c8k500023b6m10nisc5p%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyq9c8k500043b6m00zo6dwx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyq9c8k500063b6mw8jtzwx9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyq9c8k500023b6m10nisc5p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyq9c8k500013b6m3us6imq0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyq9c8k500023b6m10nisc5p%2522%252C%2522activeTabId%2522%253A%2522clyq9c8k500013b6m3us6imq0%2522%257D%252C%2522clyq9c8k500063b6mw8jtzwx9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyq9c8k500053b6mv89lkebj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fproducts%2522%257D%255D%252C%2522id%2522%253A%2522clyq9c8k500063b6mw8jtzwx9%2522%252C%2522activeTabId%2522%253A%2522clyq9c8k500053b6mv89lkebj%2522%257D%252C%2522clyq9c8k500043b6m00zo6dwx%2522%253A%257B%2522id%2522%253A%2522clyq9c8k500043b6m00zo6dwx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyq9c8k500033b6mbjhgoypf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clyq9c8k500033b6mbjhgoypf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and don't see the issue either. Gonna try to figure out what's different then in my project's setup.

**Comment by ritute** [comment] 2024-07-17 21:57
@aliemir it seems like the issue could be with using react-router (using "react-router-dom": "6.22.1"). I'm not using the one from refine at the moment.

**Comment by ritute** [comment] 2024-07-17 23:03
@aliemir here's a [reproduction](https://github.com/ritute/refine-form-demo)

The subscribe error only happens when use `useForm` from `refine`, not when using the one from `react-hook-form`.

**Comment by alicanerdurmaz** [comment] 2024-07-18 11:07
Hi @ritute, 

I found some syntax problems in your project and fixed them, but I didn't see the issue you're facing. However, I did find another error:
```md
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "@mui/material/DefaultPropsProvider"

    node_modules/@mui/lab/LoadingButton/LoadingButton.js:12:32:
      12 │ import { useDefaultProps } from '@mui/material/DefaultPropsProvider';
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@mui/material/DefaultPropsProvider" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

/Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/@mui/lab/LoadingButton/LoadingButton.js:12:32: ERROR: Could not resolve "@mui/material/DefaultPropsProvider"
    at failureErrorWithLog (/Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1059:25
    at /Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.11.0
```
This error was resolved when I updated `@mui/material` to the latest version.


Could you please recheck the project you shared? I couldn't reproduce the error you got.

**Comment by ritute** [comment] 2024-07-18 16:25
> Hi @ritute,
> 
> I found some syntax problems in your project and fixed them, but I didn't see the issue you're facing. However, I did find another error:
> 
> ```
>   ➜  Local:   http://localhost:3000/
>   ➜  Network: use --host to expose
>   ➜  press h + enter to show help
> ✘ [ERROR] Could not resolve "@mui/material/DefaultPropsProvider"
> 
>     node_modules/@mui/lab/LoadingButton/LoadingButton.js:12:32:
>       12 │ import { useDefaultProps } from '@mui/material/DefaultPropsProvider';
>          ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>   You can mark the path "@mui/material/DefaultPropsProvider" as external to exclude it from the
>   bundle, which will remove this error and leave the unresolved path in the bundle.
> 
> /Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1651
>   let error = new Error(text);
>               ^
> 
> Error: Build failed with 1 error:
> node_modules/@mui/lab/LoadingButton/LoadingButton.js:12:32: ERROR: Could not resolve "@mui/material/DefaultPropsProvider"
>     at failureErrorWithLog (/Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1651:15)
>     at /Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1059:25
>     at /Users/alicanerdurmaz/Desktop/refine-form-demo/node_modules/esbuild/lib/main.js:1527:9
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errors: [Getter/Setter],
>   warnings: [Getter/Setter]
> }
> 
> Node.js v20.11.0
> ```
> 
> This error was resolved when I updated `@mui/material` to the latest version.
> 
> Could you please recheck the project you shared? I couldn't reproduce the error you got.

@alicanerdurmaz can you make sure you're using the yarn lock file that's there with `yarn install`?  I just pulled the repo from scratch and ran into the issue I posted after a `yarn install`. It appears in the browser only, not in the terminal output. Here's a screenshot.

<img width="1585" alt="Screen Shot 2024-07-18 at 12 19 41 PM" src="https://github.com/user-attachments/assets/d849ea27-e9c8-482f-8234-3d6384bb294b">

**Comment by aliemir** [comment] 2024-07-18 22:11
Hey @ritute thank you for the update. I cloned the repo and used yarn v1 to install. Now I can reproduce the same issue 🙌

I'll try to investigate on what caused the issue but when I replace the `react-hook-form` dependency version from `7.30.0` to `^7.30.0` and that installed `7.52.1` (latest) and the error is gone and rendering is done properly. 🚀 

Can you check if updating the dependency also works for you? Do you have any limitations to keep the `react-hook-form` pinned at `7.30.0`? 🤔

**Comment by ritute** [comment] 2024-07-18 23:53
@aliemir I noticed that the Refine library was using this version 7.30.0 for `react-hook-form`, so I decided to go with that one. But I don't need to, I'll try updating it, thanks!

**Comment by ritute** [comment] 2024-07-19 01:12
@aliemir it worked with version 7.52.1 (needed to add it to resolutions to make sure it's used)

**Comment by aliemir** [comment] 2024-07-19 05:19
The version bump of `react-hook-form` to `^7.30.0` is done when we're moving to React 18. `react-hook-form` added React 18 support with [`v7.29.0`](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.29.0).

I found the issue in the `react-hook-form` package, which was resolved with PR https://github.com/react-hook-form/react-hook-form/pull/10052 and released with `7.43.5`. I didn't check our code for the `useForm` but looks like one of the changes made since the last year doesn't work with versions prior `7.43.5` 🤔 

Happy to see the issue is resolved after the update. Since we've found the exact version that resolves the issue, I think we can mark our `react-hook-form` dependency as `^7.43..5` 🙌

**Comment by aliemir** [comment] 2024-07-19 06:46
If anyone is interested on working on the fix, it should be as simple as replacing all `"react-hook-form": "^7.30.0"` with `"react-hook-form": "^7.43.5"` in the repo. @ritute I can assign this to you if you can work on it. We'll be happy to see your PR 🙏

**Comment by ritute** [comment] 2024-07-19 13:22
Okay sure I can do that. But hmm something doesn’t make sense as when I
used the older version of react-hook-form I didn’t run into this runtime
error when using the useForm from their package vs Refine’s. You can try
that repo and just instead of using Refine’s useForm, use the one from
react-hook-form.

**Comment by ritute** [comment] 2024-07-19 13:43
@aliemir is there any reason you guys don't expose `Controller` in your `@refinedev/react-hook-form` package, so that we don't need those two separate dependencies?

**Comment by aliemir** [comment] 2024-07-19 13:57
@ritute, `@refinedev/react-hook-form` is an extension package that extends `useForm` of `@refinedev/core` with abilities of `react-hook-form`. We try to keep our packages clean and don't export anything that we don't modify/extend. We take the `useForm` from `react-hook-form` and add all existing features of `@refinedev/core`'s `useForm` such as API interactions, error propagation, redirections, invalidation etc. 

For the previous question, check out the source code for the `useForm` from `@refinedev/react-hook-form`:

https://github.com/refinedev/refine/blob/master/packages/react-hook-form/src/useForm/index.ts

We're not just using or re-implementing the `useForm` hook from `react-hook-form` but we're extending it. Looks like `watch` (`useSubscribe` under the hood -the one causing the errors-) is used for notifying the user on unsaved changes and for the auto-save feature. Since those are not present in `react-hook-form`'s `useForm`, we don't get any errors if we use it directly. 

I hope I clarified the difference and the reason behind two packages and two hooks ✌️

**Comment by ritute** [comment] 2024-07-19 17:02
@aliemir getting this when running `pnpm install` in latest master.

<img width="952" alt="Screen Shot 2024-07-19 at 12 59 12 PM" src="https://github.com/user-attachments/assets/fdbffd2f-30eb-4a1f-b04d-64072694aaca">

**Comment by ritute** [comment] 2024-07-19 18:15
@aliemir ah, oh my, I somehow added that... 😂. All good! BTW, there are several tests that fail in master for me - looks like a timezone related issue with MUI DateField.

<img width="1099" alt="Screen Shot 2024-07-19 at 2 11 55 PM" src="https://github.com/user-attachments/assets/8e6a7ef5-8696-44b6-b118-de81a6322a9c">
<img width="1096" alt="Screen Shot 2024-07-19 at 2 11 40 PM" src="https://github.com/user-attachments/assets/c78c31e5-1546-48dc-9a42-d067dc4e08da">

**Comment by ritute** [comment] 2024-07-19 18:19
https://github.com/refinedev/refine/pull/6161

**Closed** 2024-08-05 10:32 UTC
Labels: bug, good first issue
