### ISSUE TITLE
[BUG] Table representation is broken in `Data Fetching` guide

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5502] opened 2024-01-11 13:34 UTC
### Describe the bug

The table representation within the relationship section of the data-fetching documentation looks broken.

### Steps To Reproduce

1. Go to https://refine.dev/docs/guides-concepts/data-fetching/#relationships
2. Look at the table representation.

### Expected behavior

Borders should be aligned.

### Screenshot

![image](https://github.com/refinedev/refine/assets/23058882/a5a4ea4e-9ddd-493d-9a99-2b5fefe282ba)

**Comment by amirk85** [comment] 2024-01-11 22:09
I believe it's already aligned, working fine for me

![Screenshot from 2024-01-12 03-37-15](https://github.com/refinedev/refine/assets/96424514/573c83a3-0cb8-449f-b384-7e17151d8100)

**Comment by AnasGrzor** [comment] 2024-01-11 22:13
> I believe it's already aligned, working fine for me @alicanerdurmaz
> 
> ![Screenshot from 2024-01-12 03-37-15](https://private-user-images.githubusercontent.com/96424514/296065708-573c83a3-0cb8-449f-b384-7e17151d8100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTEzNDgsIm5iZiI6MTcwNTAxMTA0OCwicGF0aCI6Ii85NjQyNDUxNC8yOTYwNjU3MDgtNTczYzgzYTMtMGNiOC00NDlmLWIzODQtN2UxNzE1MWQ4MTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIyMTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZDkyYjUzNDJkNGRlNWIzOTE2ZjhjYTg4MDljOGJlNTE1NTYzYmJkNzFlODg3MzY3YWZkOGQxZmQ4ZmU0NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.76TsDWM81gatJVClX4MtQT_qVdtK5CyBfaGJcwOKga4)

If you check out the docs you can see the borders are misaligned. In my vscode it also appeared fine but for some reason in the docs it's weird.

**Comment by amirk85** [comment] 2024-01-11 22:42
@AnasGrzor  not able to see the screenshot you attached.
And also I don't see any misalignment in the doc as well

attaching a short clip

[Screencast from 12-01-24 04:09:05 AM IST.webm](https://github.com/refinedev/refine/assets/96424514/e08487f5-89a2-480a-a93f-442ea7fe69f4)

**Comment by AnasGrzor** [comment] 2024-01-11 22:46
@amirk85 
![Screenshot_2024-01-12-03-45-48-050_com android chrome](https://github.com/refinedev/refine/assets/103470289/4410a305-0fe0-4a57-9542-c1e691658e8a)
This is in chrome

**Comment by alicanerdurmaz** [comment] 2024-01-12 07:15
Hello @AnasGrzor and @amirk85, thanks for helping Refine. 

It's an interesting problem 🤔. I will investigate too.

**Comment by aliemir** [comment] 2024-01-12 07:50
Hey everyone, thank you for your interests and effort in this issue! I've suspected that this is happening due to fallbacks provided in the font family definition. I've checked in my local to update the `tailwind.config.js` like this for the `JetBrains Mono`:

```diff
"jetBrains-mono": [
                    "JetBrains Mono",
-                   ...defaultTheme.fontFamily.mono,
+                   "monospace"
                ],
```

The issue resolved for me.

Can anyone check if the same solution works for them as well? If its resolved, we'll be happy to see a PR addressing this change 🙏

**Comment by AnasGrzor** [comment] 2024-01-12 10:31
![image](https://github.com/refinedev/refine/assets/103470289/e0a005b3-0904-48da-9784-bb286d8a943e)
I did the change but it's still the same
![image](https://github.com/refinedev/refine/assets/103470289/aa057937-513d-45a1-a017-9f1ffb7b3dca)

**Comment by Conqxeror** [comment] 2024-01-17 06:01
It is caused by `font-family: Source Code Pro`  @aliemir @BatuhanW @alicanerdurmaz 
 
# With Font :

## SS for issue.
![Screenshot 2024-01-17 112148](https://github.com/refinedev/refine/assets/110852661/d4c8d460-31cf-44f7-82e0-9d1701cf42e8)

## Reason for issue.
![Screenshot 2024-01-17 112203](https://github.com/refinedev/refine/assets/110852661/b69bdd9a-d5f5-4494-9e3c-c004e5f395cc)

# Without Font

## Issue Fix If:
![Screenshot 2024-01-17 112751](https://github.com/refinedev/refine/assets/110852661/7c14b854-fe2b-4326-b2bf-c3129a52d152)

## After removal of:  `font-family: Source Code Pro` :
![Screenshot 2024-01-17 112819](https://github.com/refinedev/refine/assets/110852661/6db9e3e5-c4e8-4175-9626-a024a570505b)

**Comment by notnick2** [comment] 2024-01-21 12:58
Is the issue resolved? If not, I'm excited to work on resolving it.

**Comment by alicanerdurmaz** [comment] 2024-01-22 14:41
@notnick2 Thanks 🚀, I assigned the issue to you.

**Comment by alicanerdurmaz** [comment] 2024-02-06 07:16
@CodeKage25 Thanks, I assigned it to you.

**Comment by domlimm** [comment] 2024-03-09 14:31
@alicanerdurmaz Hey Alican, may I have a go at this?

**Comment by BatuhanW** [comment] 2024-03-12 12:18
Hey @domlimm let us know when you can work on this, let's assign to you.

**Comment by domlimm** [comment] 2024-03-22 03:49
@BatuhanW Hey Bathuan! I did some digging last week and just for an hour before writing this.. Seems okay on VSCode (but I suppose that's not the case/what we're trying to fix). However, I checked on prod and it seems slightly off. I'm on macOS, checked on Chrome.

VSCode:
<img width="1438" alt="image" src="https://github.com/refinedev/refine/assets/46486515/2bcc587d-650c-4caa-8f0e-3b324004c384">

Chrome:
<img width="1440" alt="image" src="https://github.com/refinedev/refine/assets/46486515/a78fa15d-5f89-47ae-9c26-6a3e0fcd2e3f">

Safari:
<img width="1552" alt="image" src="https://github.com/refinedev/refine/assets/46486515/c660168e-39f1-47aa-9b96-8c30baa24090">

On Windows Chrome (both locally and prod):
Exactly what's shown in the opening of this issue.

I am actually struggling to find out the root cause. It's odd because it's a table in markdown.

**Comment by JamieBort** [comment] 2024-03-25 22:11
There's a lot of hands working on this issue. If there is anything that I can do to help, please let me know.
Otherwise I'll continue to look for another issue to work on. 
FWI worth, I am new to this repo.

**Closed** 2024-05-31 23:48 UTC
Labels: bug, documentation, good first issue, wontfix
